- name: Install nfs-common (Debian)
  package: name=nfs-common state=present
  when: ansible_os_family == 'Debian'

- name: Install nfs-utils (RedHat)
  package: name=nfs-utils state=present
  when: ansible_os_family == 'RedHat'

- name: Get mount source URL with availability zone
  action: uri url=http://169.254.169.254/latest/meta-data/placement/availability-zone return_content=yes
  register: availability_zone

- name: Create directories for the mounts
  file: path={{ item.path }} state=directory mode={{ item.mode | default("0644") }} owner={{ item.owner | default("root") }} group={{ item.group | default("root") }}
  with_items: "{{ aws_efs_paths }}"

- name: Mount paths
  mount: name={{ item.path }} src={{ availability_zone.content }}.{{ item.filesystem_id }}.efs.{{ item.region }}.amazonaws.com:/ fstype=nfs4 opts="nfsvers=4.1" state=mounted
  with_items: "{{ aws_efs_paths }}"
